### ISSUE TITLE
dump cart to cia failure on 128gb cards

### ISSUE THREAD

**Issue by pcs3rd** [d0k3/Hourglass9#22] opened 2017-03-06 21:59 UTC
on my 128GB sd card, I was unable to dump a game cart to a .cia, or any for that matter, I have tried the same card and others with another 32gb sd card and it works just fine, on the 128GB card,it is complaining that the cia doesn't not look like a .cia, and fbi complains about size issues with the .cia

**Comment by james-d-elliott** [comment] 2017-03-07 00:40
Have you used h2testw on the 128gb sd card? Bad size issues and bad cia's can be caused by fake SD cards quite easily. For ref I use my 128GB fine, so it's unlikely to be a H9 issue.

**Comment by d0k3** [comment] 2017-03-07 01:04
Seconding this, this looks like either a SD card issue, or a SD card formatting issue. I know it's no fun reformatting a 128GB card, but there may be no way around it. Using h2testw is also required to make 100% sure this SD card is not a fake.

What you could try quickly is using the cart dumper included in GodMode9 / SafeMode9 (C: is the cartridge drive, press A on the .3DS to convert to CIA).

**Comment by d0k3** [comment] 2017-03-08 15:52
@pcs3rd - we need more info. Otherwise I'll have to assume defective SD and close this.

**Closed as completed** 2017-03-24 20:55 UTC
